"""add email to company

Revision ID: 782b6e3f466a
Revises: 
Create Date: 2026-03-23 10:36:43.376441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782b6e3f466a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
